### ISSUE TITLE
Error when run with --'use-strict' mode

### ISSUE THREAD

**Issue by takaaptech** [mcavage/node-assert-plus#23]
Hi, I am running restify example in node version 5.0.0 and with --use-strict flag. How can i fix this error?
Thank so much!

macbooks-MacBook-Pro-2:restify macbook$ node --'use-strict' main.js 
/Users/macbook/nodejs/restify/node_modules/assert-plus/assert.js:41
stackFunc = stackFunc || _assert.caller;
^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
at _assert (/Users/macbook/nodejs/restify/node_modules/assert-plus/assert.js:41:49)

**Comment by AlexTes** [comment]
Just to provide some context. This means that using just node, without babel, and restify, is now not possible if you'd also like to not insert 'use strict' at the top of every file. Which to my surprise seems quite  the rare use case.

**Comment by plurry** [comment]
This is fixed in the current version of the library, but Restify is still using an old version, so it's really a Restify problem. I think this issue can be closed.

**Comment by AlexTes** [comment]
Ah! Good to hear. Seems right to close this then. Long time ago but I still wonder.. Does everyone use babel? No one use restify? Or does everyone have no issue putting 'use strict' at the top of every file?
