### ISSUE TITLE
assert.number(NaN) should fail or add assert.finite

### ISSUE THREAD

**Issue by adamschmideg** [mcavage/node-assert-plus#4]
I'd expect assert.number(NaN) to fail, but it doesn't.  Either it should fail, or you can add assert.finite which fails for NaN.

**Comment by trentm** [comment]
Node that assert-plus@1.0.0 changed this again to allow infinity in `assert.number` (e.g. `Infinity`) and added `assert.finite`.  I can't help but think that disallowing Infinity for `assert.number` wasn't totally expected/intended.
